# Generated by Django 3.2.4 on 2021-06-17 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_de_publicacao',
            field=models.DateTimeField(blank=True, default='17/06/2021'),
        ),
    ]
