# Generated by Django 3.2.4 on 2021-06-17 21:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gkapp', '0004_alter_produto_data_de_publicacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='informacoes',
            field=models.TextField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_de_publicacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 17, 18, 18, 10, 443242)),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanho',
            field=models.TextField(max_length=200),
        ),
    ]
