# Generated by Django 3.2.4 on 2021-06-18 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gkapp', '0006_auto_20210617_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data_de_publicacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 18, 14, 46, 28, 781875)),
        ),
    ]
