# Generated by Django 3.2.4 on 2021-06-22 22:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gkapp', '0008_auto_20210622_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='data_de_publicacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 6, 22, 19, 15, 30, 200627)),
        ),
    ]
